name: deploy unicode-api

on:
  push:
    branches:
      - 'main'

jobs:
  bake:
    name: Build docker image for unicode-api and deploy to dokku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Bake unicode-api image and push to github container registry
        uses: docker/bake-action@v3.1.0
        with:
          files: ./docker-bake.hcl
          targets: unicode-api
          push: true
      - name: Deploy unicode-api docker image to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_HOST }}:22/unicode-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ghcr.io/${{ github.repository_owner }}/unicode-api:${{ github.sha }}
