name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@main
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_HOST }}:22/unicode-api'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
